locations = ['california', 'indiana', 'texas', 'florida', 'netherlands', 'tHE END']
print("original")
print(locations)
print("sorted")
print(sorted(locations))
print("original")
print(locations)
print("sorted")
print(sorted(locations))
print("backword sorted")
print(sorted(locations, reverse=True))
print("original")
print(locations)
locations.reverse()
print("reverse original")
print(locations)
locations.reverse()
print("back to the original")
print(locations)
locations.sort()
print("perma sort")
print(locations)
locations.reverse()
print("sort sort")
print(locations)


